"""生成 etl.ipynb —— 一条数据从 Seek 到会员邮箱，再从库里读回来。

    python3 build_etl.py

和 pipeline.ipynb 的分工：
  pipeline.ipynb  只讲【抓取那一段】，从网页到 jobs.db
  etl.ipynb       讲【全链路】，而且两头都讲：入库 in，出库 out

不打码。这是管理员自己的库、自己的会员，工具对使用者藏数据是没用的工具。
No masking: it is the operator's own database.
"""
import json
import pathlib

def md(*l): return {"cell_type": "markdown", "metadata": {}, "source": "\n".join(l)}
def code(*l): return {"cell_type": "code", "execution_count": None, "metadata": {},
                      "outputs": [], "source": "\n".join(l)}
def io(does, gets, sees, wrong=None):
    o = [f"> **这一格干什么 what** {does}  ",
         f"> **输入 input** {gets}  ",
         f"> **应该看到 expected** {sees}"]
    if wrong: o.append(f"  \n> **看到别的 otherwise** {wrong}")
    return md(*o)

C = []

# ══════════════════════ 封面 ═══════════════════════════════════════════════
C.append(md(
"# 全链路 ETL · 进库与出库",
"## 一条数据从 Seek 的一张网页，到会员的收件箱，再读回来",
"",
"**这份笔记本不花一分钱。** 它只读已有的数据，不调用任何 AI，不发任何邮件。",
"",
"---",
"",
"### 和 `pipeline.ipynb` 的分工",
"",
"| | 讲什么 |",
"|---|---|",
"| `pipeline.ipynb` | 只讲**抓取那一段**：网页 → jobs.db |",
"| **这一份** | 讲**全链路**，而且**两头都讲**：入库 in / 出库 out |",
"",
"### 八层",
"",
"```",
"  ── 入库 IN ─────────────────────────────────────────────",
"  ①  一张网页                    Seek HTML          存档页面，离线可跑",
"      ↓  抽取",
"  ②  一个 dict                   本地对象           全是【原文】",
"      ↓  save_job",
"  ③  jobs.db 的一行              本机 SQLite        14 列",
"      ↓  to_ingest()",
"  ④  一个 JSON 载荷              HTTP POST          这里第一次算出时间戳",
"      ↓  /api/ingest/jobs",
"  ⑤  生产 D1 的一行              事实行             加上 region / 族 / 级别",
"",
"  ── 出库 OUT ────────────────────────────────────────────",
"      ↓  buildDigest",
"  ⑥  一个人的候选池              36 小时窗口        + 排除已投递",
"      ↓  匹配 / 排序 / 封顶",
"  ⑦  一封邮件 + 三张台账          发出去的痕迹       job_sends / digest_runs / …",
"      ↓  门户读回来",
"  ⑧  会员看到的东西              续页 my-jobs       快照，不是实时查询",
"```",
"",
"### 一个原则贯穿全程",
"",
"**每一层都打印，而且打印【全部】** —— 会员邮箱、姓名、岗位链接，一个不省。",
"这是你自己的库。一个对管理员藏数据的工具是没用的工具。",
"",
"> ⚠️ 这份 notebook 存盘时**不要带输出**（`Kernel → Restart & Clear Output`）。",
"> 输出里有真实会员数据，而 `.ipynb` 是要进 git 的。这是操作习惯，不是限制 ——",
"> 你随时可以跑，随时看到全部。",
))

# ══════════════════════ 术语 ═════════════════════════════════════════════
C.append(md(
"---",
"# 术语对照 · glossary",
"",
"| 中文 | English | 一句话 |",
"|---|---|---|",
"| 抽取 | **extract** | 从 HTML 里把字段抠出来 |",
"| 变换 | **transform** | 改格式、算派生值，如 `'10h ago'` → `1786398766` |",
"| 装载 | **load** | 写进数据库 |",
"| 原文字段 | **raw field** | 一字不改抄下来的，如 `title_raw` |",
"| 派生字段 | **derived** | 我们判断出来的，如 `region` / `role_family` |",
"| 归一化 | **normalisation** | 杂乱原文 → 固定取值 |",
"| 幂等 | **idempotent** | 同一件事做两次，结果和做一次一样 |",
"| 候选池 | **pool** | 这一封信【可能】选到的全部岗位 |",
"| 快照 | **snapshot** | 发信那一刻定格，之后库怎么变都不影响它 |",
"| 事实行 | **fact row** | 存原始事实的一行，一行一个岗位 |",
"",
"> **术语一律保留英文。** 你要教组员，他们查资料看到的是英文。",
))

# ══════════════════════ 工具 ═════════════════════════════════════════════
C.append(md("---", "# 准备：会讲解自己的打印工具"))
C.append(io("定义 `layer()` / `audit()` / `verdict()` / `row()`。"
            "每一格都会打印【现在第几层】【在验什么】【结论】【这意味着什么】。",
            "无", "`工具就绪 · ready`"))
C.append(code(
"import sqlite3, json, pathlib, re, subprocess, os, textwrap",
"from datetime import datetime, timezone, timedelta",
"",
"HUNTER = pathlib.Path('../flowgt-job-hunter').resolve()",
"SITE   = pathlib.Path('../flowgt-website').resolve()",
"assert HUNTER.exists() and SITE.exists(), '三个仓库要在同一级目录下'",
"",
"TOTAL = 8",
"",
"def layer(n, zh, en):",
"    bar = '█'*n + '░'*(TOTAL-n)",
"    side = '入库 IN' if n <= 5 else '出库 OUT'",
"    print(f'\\n{\"═\"*76}')",
"    print(f'  第 {n} / {TOTAL} 层   {bar}   {side}')",
"    print(f'  {zh}')",
"    print(f'  {en}')",
"    print('═'*76)",
"",
"def audit(what, why):",
"    print(f'\\n🔍 AUDIT：{what}')",
"    print(f'   为什么要验：{why}\\n')",
"",
"def verdict(ok, finding, means):",
"    print(f'   {\"✓\" if ok else \"✗\"} 结论 finding：{finding}')",
"    print(f'   → 意味着 means：{means}')",
"",
"def row(d, title=None, width=104):",
"    \"\"\"把一行/一个 dict 全部打印出来。不省略、不打码。\"\"\"",
"    if title: print(f'   {title}')",
"    if d is None: print('     （None）'); return",
"    for k, v in dict(d).items():",
"        s = repr(v)",
"        if len(s) > width: s = s[:width-3] + '…'",
"        print(f'     {k:<18} {s}')",
"",
"def d1(sql, label=None):",
"    \"\"\"跑一句生产库的只读 SQL。",
"",
"    CI=1 / WRANGLER_SEND_METRICS=false：npx 在非交互子进程里会去问遥测，",
"    没有终端就【静静地什么都不输出】。test/run.sh 和 bin/hunt-status 都踩过。",
"    \"\"\"",
"    env = dict(os.environ, CI='1', WRANGLER_SEND_METRICS='false')",
"    p = subprocess.run(['npx','wrangler','d1','execute','flowgt','--remote','--json',",
"                        '--command', sql], cwd=SITE, env=env,",
"                       capture_output=True, text=True)",
"    b = p.stdout or ''",
"    if '\"error\"' in b:",
"        note = ''",
"        try:",
"            e = json.JSONDecoder().raw_decode(b[b.index('{'):])[0]['error']",
"            note = (e.get('notes') or [{}])[0].get('text','')",
"        except Exception: pass",
"        raise RuntimeError(f'查库失败：{note or b[:300]}')",
"    out, _ = json.JSONDecoder().raw_decode(b[b.index('['):])",
"    res = out[0]['results']",
"    if label: print(f'   {label}：{len(res)} 行')",
"    return res",
"",
"print('工具就绪 · ready')",
))

# ══════════════════════ ① 网页 ════════════════════════════════════════════
C.append(md(
"---",
"# ① 一张网页 · the raw page",
"",
"**代码在** `scraper.py` · `extract_job_cards()`",
"",
"起点是 Seek 搜索结果页的 HTML。这一层用 `audit-local/` 里的**存档页面**，",
"所以它**离线可跑、结果确定** —— 每次跑都是同一张卡片，适合教学和回归。",
"",
"想看今天的真实页面：`python3 audit_seek.py --out audit-local` 重新拍一张。",
))
C.append(io("从存档 HTML 里切出【一张】岗位卡片，把原始标记打印出来。",
            "`../flowgt-job-hunter/audit-local/*.html`",
            "一张卡片的 HTML 片段，以及它上面所有 `data-automation` 属性",
            "没有存档 → 先跑 `python3 audit_seek.py --out audit-local`"))
C.append(code(
"layer(1, '一张网页', 'the raw page — archived HTML, offline and deterministic')",
"",
"pages = sorted((HUNTER/'audit-local').glob('*.html'))",
"assert pages, '没有存档页面，先跑：python3 audit_seek.py --out audit-local'",
"H = pages[0].read_text(errors='ignore')",
"print(f'   用 {pages[0].name}，{len(H):,} 字')",
"",
"idx = [m.start() for m in re.finditer(r'data-testid=\"job-card\"', H)]",
"CARD = H[idx[0]:idx[1]]          # 第一张卡片的完整 HTML",
"print(f'   页面上 {len(idx)} 张卡片，取第 1 张，{len(CARD):,} 字\\n')",
"",
"audit('这张卡片上到底有哪些字段',",
"      '选择器写错了不会报错 —— 它返回空字符串。所以先看【页面上有什么】，'",
"      '再看【我们取了什么】，两边对不上才是真的问题。')",
"attrs = sorted(set(re.findall(r'data-automation=\"([^\"]+)\"', CARD)))",
"print('   卡片上的 data-automation：')",
"for a in attrs: print(f'     {a}')",
"verdict(True, f'{len(attrs)} 个属性',",
"        '下一层会逐个对照：我们用的选择器，是不是都在这张清单里。')",
"",
"print('\\n   ── 卡片的可见文字（去掉标签）──')",
"txt = re.sub(r'\\s+',' ', re.sub(r'<[^>]+>',' ', CARD)).strip()",
"print(textwrap.fill(txt[:700], width=90, initial_indent='     ', subsequent_indent='     '))",
))

# ══════════════════════ ② dict ════════════════════════════════════════════
C.append(md(
"---",
"# ② 一个 dict · extraction",
"",
"**代码在** `scraper.py:extract_job_cards()`",
"",
"这一层把 HTML 变成 python 对象。**全是原文**，一个字都不改 ——",
"归一化要等到第 ⑤ 层在服务端做。",
"",
"这里有一处刻意的区分，别弄混：",
"",
"| 字段 | 从哪来 | 多大 | 什么时候有 |",
"|---|---|---|---|",
"| `teaser` | 列表卡片自带 | ~250 字 | **每次采集都有**，不花额外请求 |",
"| `jd` | 详情页 | 1.5–5 k 字 | 只在 `--with-jd` |",
"",
"`teaser` **不能冒充** `jd`：它是广告的三条要点，拿它去让 Claude 打 0–100 分，",
"会得到**自信的错误分数** —— 比没有分数更糟，而且不报错。",
))
C.append(io("对同一张卡片跑真正的抽取函数，把抽出来的每一个字段打印出来。",
            "上一格的 CARD",
            "一个 dict，14 个键，全是原文",
            "某个字段是空串 → 那个选择器在这张页面上匹配不到"))
C.append(code(
"layer(2, '一个 dict', 'extraction — HTML to a python object, all raw')",
"import sys; sys.path.insert(0, str(HUNTER))",
"import importlib, scraper; importlib.reload(scraper)",
"",
"# extract_job_cards 要一个 playwright page 对象。这里不起浏览器 ——",
"# 用同样的正则从存档 HTML 里抽，验的是【选择器对不对】，不是 playwright 对不对。",
"def pick(auto, c=CARD):",
"    m = re.search(r'data-automation=\"'+auto+r'\"[^>]*>(.*?)</', c, re.S)",
"    return re.sub(r'\\s+',' ', re.sub(r'<[^>]+>','',m.group(1))).strip() if m else ''",
"",
"plain = re.sub(r'\\s+',' ', re.sub(r'<[^>]+>',' ', CARD))",
"wt = ''",
"for m in re.findall(r'This is an? ([^.<>]{2,24}?) job', plain):",
"    if m.strip().lower() not in ('featured','promoted','sponsored'): wt = m.strip(); break",
"bullets = [re.sub(r'\\s+',' ',re.sub(r'<[^>]+>','',x)).strip()",
"           for x in re.findall(r'<li[^>]*>(.*?)</li>', CARD, re.S)]",
"",
"href = re.search(r'data-automation=\"jobTitle\"[^>]*href=\"([^\"]+)\"', CARD) or \\",
"       re.search(r'href=\"([^\"]+)\"[^>]*data-automation=\"jobTitle\"', CARD)",
"JOB = {",
"    'title':       pick('jobTitle'),",
"    'url':         'https://www.seek.co.nz' + href.group(1) if href else '',",
"    'company':     pick('jobCompany'),",
"    'location':    pick('jobLocation'),",
"    'salary':      pick('jobSalary'),",
"    'job_type':    wt,",
"    'posted_date': pick('jobListingDate'),",
"    'job_class':   pick('jobClassification'),",
"    'sub_class':   pick('jobSubClassification'),",
"    'teaser':      ' · '.join([b for b in bullets if b] +",
"                              ([pick('jobShortDescription')] if pick('jobShortDescription') else [])),",
"    'jd':          '',",
"    'keyword':     'class:information-communication-technology',",
"}",
"row(JOB, '抽出来的 dict —— 全部字段：')",
"",
"audit('有没有字段是空的',",
"      '空字符串是选择器失效的唯一症状，而它不报错。这个仓库因为它坏过四次。')",
"empty = [k for k,v in JOB.items() if not str(v).strip() and k != 'jd']",
"verdict(not empty, f'空字段：{empty or \"无\"}（jd 不算，它要详情页才有）',",
"        'jd 为空是正常的：日常采集不抓正文。其它字段为空要去查 scraper.py 的选择器。')",
"",
"audit('工作类型是从哪读到的',",
"      '卡片上【没有】任何 data-automation 装工作类型 —— 唯一带 WorkType 的属性'",
"      '属于筛选面板，那是页面家具不是岗位数据。')",
"verdict(bool(wt), f'读到 {wt!r}，来源是给读屏软件的那句 \"This is a … job\"',",
"        '这是无障碍文案不是数据契约，Seek 改文案它就没了 —— '",
"        'test_selectors.py 里有一条断言守着它。')",
))

# ══════════════════════ ③ jobs.db ═════════════════════════════════════════
C.append(md(
"---",
"# ③ jobs.db 的一行 · local staging",
"",
"**代码在** `scraper.py:save_job()` + `job_id()`",
"",
"两件事在这一层定下来，两件都出过事：",
"",
"**身份**。Seek 的结果链接带**每次搜索都不一样**的追踪码。对整条 URL 取 md5，",
"同一个岗位在 33 个关键词下会得到 33 个不同的 id —— 生产库里岗位 `93814499` "
"因此存过**四份**。现在用 Seek 自己的岗位号。",
"",
"**自愈**。`INSERT OR IGNORE` 遇到已存在的行**直接跳过**，所以用旧代码抓进来的行",
"永远补不上后来才修好的字段。现在重抓会填**空格子**，但绝不覆盖已有值 ——",
"`posted_date` 刻意排除，它存的是相对时间，要配着当初的 `scraped_at` 才有意义。",
))
C.append(io("看这一行在本地库里真实的样子，并验证 id 的稳定性。",
            "`../flowgt-job-hunter/jobs.db`",
            "一行 14 列的真实数据 + 两条 id 断言"))
C.append(code(
"layer(3, 'jobs.db 的一行', 'local staging — identity and self-healing')",
"con = sqlite3.connect(f'file:{HUNTER}/jobs.db?mode=ro', uri=True)",
"con.row_factory = sqlite3.Row",
"",
"cols = [r[1] for r in con.execute('PRAGMA table_info(jobs)')]",
"tot,  = con.execute('SELECT COUNT(*) FROM jobs').fetchone()",
"print(f'   jobs.db：{tot} 行 × {len(cols)} 列')",
"print(f'   列：{cols}\\n')",
"",
"# 用刚才那张卡片的岗位号找它；找不到就用最新的一行",
"LOCAL = con.execute('SELECT * FROM jobs WHERE job_url LIKE ?',",
"                    (f'%{scraper.job_id(JOB[\"url\"]).replace(\"seek-\",\"\")}%',)).fetchone()",
"if LOCAL is None:",
"    LOCAL = con.execute('SELECT * FROM jobs ORDER BY scraped_at DESC LIMIT 1').fetchone()",
"    print('   （存档那个岗位不在库里，改用最新抓到的一行）')",
"row(LOCAL, '本地库里的一整行：')",
"",
"audit('id 稳不稳定',",
"      '同一个岗位在不同关键词下 URL 不一样。id 跟着 URL 变，就会一岗多行。')",
"a = scraper.job_id('https://www.seek.co.nz/job/93814499?type=standard&ref=search-A')",
"b = scraper.job_id('https://www.seek.co.nz/job/93814499?type=promoted&ref=search-B#sol=x')",
"verdict(a == b == 'seek-93814499', f'两条带不同追踪码的 URL → {a} / {b}',",
"        '一致 = 重复抓取不会灌水。不一致 = 去查 scraper.py 的 job_id()。')",
"",
"uniq, = con.execute('SELECT COUNT(DISTINCT id) FROM jobs').fetchone()",
"verdict(uniq == tot, f'{tot} 行 / {uniq} 个不重复 id', '相等才说明没有一岗多行。')",
"",
"audit('每一列的填充率', '「这个字段一直是空」只有填充率看得出来。')",
"print(f'   {\"列\":<14}{\"有值\":>8}{\"占比\":>8}')",
"for c in cols:",
"    n, = con.execute(f'SELECT COUNT(*) FROM jobs WHERE {c} IS NOT NULL AND {c}!=\"\"').fetchone()",
"    mark = '✓' if n/tot > .9 else ('!' if n else '✗')",
"    print(f'   {mark} {c:<12}{n:>8}{100*n/tot:>7.1f}%')",
))

# ══════════════════════ ④ 载荷 ════════════════════════════════════════════
C.append(md(
"---",
"# ④ 一个 JSON 载荷 · transform",
"",
"**代码在** `push.py:to_ingest()`",
"",
"这一层是**整条链路上唯一一次真正的变换**：`'10h ago'` 这个字符串在这里变成时间戳。",
"",
"两条规矩，都是事故换来的：",
"",
"**解析不出来就返回 `None`，不许猜。** 原来的代码解析失败会回落到 `scraped_at`，",
"于是每个岗位的 `posted_at` 都等于我们抓它的那一刻，**全库看起来都是 0 天新**。",
"一个假的时间戳比没有时间戳危险得多 —— 没有的时候你知道自己不知道。",
"",
"**年龄的锚点是【抓取时刻】，不是【推送时刻】。** 卡片写的 `'5h ago'` 是在我们抓它",
"的时候为真的。用推送时刻当基准，一个昨天抓的岗位今天推会年轻一整天，",
"而且每推一次刷新一次 —— 它**永远不会变老**。",
))
C.append(io("跑真正的 `to_ingest()`，把【送出去的那个 JSON】原样打印。",
            "上一格的本地行",
            "一个 9 键的 dict，其中 `postedAt` 是 epoch 秒"))
C.append(code(
"layer(4, '一个 JSON 载荷', 'transform — the only real transformation in the chain')",
"import push; importlib.reload(push)",
"",
"D = dict(LOCAL)",
"PAYLOAD = push.to_ingest(D)",
"row(PAYLOAD, '真正会被 POST 出去的 JSON：')",
"",
"audit('时间戳是怎么算出来的', '这是全链路唯一一次真正的变换，也是出过事的那一处。')",
"anchor = push.scraped_at_utc(D['scraped_at'])",
"print(f'     卡片上写的         {D[\"posted_date\"]!r}')",
"print(f'     抓取时刻（本机）    {D[\"scraped_at\"]}')",
"print(f'     抓取时刻（UTC）     {anchor}')",
"print(f'     算出的 postedAt     {PAYLOAD[\"postedAt\"]}')",
"if PAYLOAD['postedAt']:",
"    when = datetime.fromtimestamp(PAYLOAD['postedAt'])",
"    age  = (datetime.now() - when).total_seconds()/3600",
"    print(f'     也就是             {when:%Y-%m-%d %H:%M}（{age:.1f} 小时前）')",
"",
"wrong = push.parse_age(D['posted_date'])   # 不传锚点 = 用现在，错的那种算法",
"if wrong and PAYLOAD['postedAt']:",
"    drift = (wrong - PAYLOAD['postedAt'])/3600",
"    verdict(True, f'用推送时刻当基准会年轻 {drift:.1f} 小时',",
"            '差值等于「抓取到现在」过了多久。每推一次刷新一次，岗位就永远不过期。')",
"",
"audit('解析不出来的时候会怎样', '编一个日期出来，比留空危险得多。')",
"for s in ['10h ago','2d ago','40m ago','Featured','New to you','']:",
"    v = push.parse_age(s, anchor)",
"    print(f'     {s!r:<14} → {v if v else \"None（不知道就是不知道）\"}')",
"verdict(push.parse_age('Featured', anchor) is None, \"'Featured' → None\",",
"        '置顶岗位不显示年龄。返回 None → posted_at 为空 → 发信的硬条件挡住它。'",
"        '正确的补法是去详情页问真日期（bin/backfill-detail），不是编一个。')",
))

# ══════════════════════ ⑤ D1 ══════════════════════════════════════════════
C.append(md(
"---",
"# ⑤ 生产 D1 的一行 · ingest + normalise",
"",
"**代码在** `functions/api/ingest/jobs.js`",
"",
"服务端做三件本地不做的事：",
"",
"1. **闸门** `isITRole()` —— 全链路**唯一**一道「收不收」。摘要那一步只排序不删岗，",
"   前提就是这里守住了，否则 Cabin Crew 会出现在数据分析师的邮件里。",
"2. **归一化** —— `region` / `role_family` / `seniority` / `role_group` / 薪资区间。",
"   全部在**入库那一刻**算好存下来，**不在读取时算**：月报要的是当时的判断。",
"3. **生命周期** —— `first_seen_day` / `last_seen_day` / `is_open`。",
"",
"⚠️ **更新分支不碰 `posted_at`**：",
"```sql",
"UPDATE jobs SET last_seen_day = ?, is_open = 1, updated_at = ? WHERE id = ?",
"```",
"这一条很重要 —— 它意味着 `posted_at` **只在首次入库时写一次**，之后重推多少次都不变。",
))
C.append(io("把同一个岗位在生产库里的样子拉回来，和第 ③ 层逐字段对照。",
            "生产 D1（需要 wrangler 登录）",
            "一行 22 列，其中派生字段是本地没有的"))
C.append(code(
"layer(5, '生产 D1 的一行', 'ingest + normalise — the fact row')",
"ext = PAYLOAD['externalId']",
"got = d1(f\"SELECT * FROM jobs WHERE external_id = '{ext}'\")",
"if not got:",
"    print(f'   {ext} 不在生产库里（可能还没推）。改用最新入库的一行：')",
"    got = d1('SELECT * FROM jobs ORDER BY created_at DESC LIMIT 1')",
"PROD = got[0]",
"row(PROD, '生产 D1 里的一整行：')",
"",
"audit('哪些是原文，哪些是我们判断出来的',",
"      '把两者分清楚，是「一年后还能不能重算」的前提。')",
"RAW  = ['external_id','title_raw','company','location_raw','url','salary_period']",
"DERV = ['region','role_family','role_group','seniority','salary_min','salary_max','posted_at']",
"LIFE = ['first_seen_day','last_seen_day','is_open','taxonomy_ver']",
"for name, keys in [('原文 raw', RAW), ('派生 derived', DERV), ('生命周期 lifecycle', LIFE)]:",
"    print(f'\\n   {name}')",
"    for k in keys:",
"        if k in PROD: print(f'     {k:<18} {PROD[k]!r}')",
"",
"audit('本地那一行和生产这一行，对得上吗', '对不上说明变换那一层动了不该动的东西。')",
"pairs = [('job_title','title_raw'),('company','company'),('location','location_raw'),('job_url','url')]",
"bad = []",
"for l, p in pairs:",
"    lv, pv = (D.get(l) or '').strip(), (PROD.get(p) or '')",
"    same = lv == pv",
"    print(f'     {l:<12} {lv[:44]!r:<48} {\"==\" if same else \"!=\"} {pv[:44]!r}')",
"    if not same: bad.append(l)",
"verdict(not bad, f'不一致的字段：{bad or \"无\"}',",
"        '原文字段必须一字不改地穿过去 —— 它们是「一年后重算」的唯一依据。')",
))

# ══════════════════════ ⑥ 候选池 ══════════════════════════════════════════
C.append(md(
"---",
"# ⑥ 一个人的候选池 · the pool（出库第一步）",
"",
"**代码在** `functions/api/admin/send-digest.js:buildDigest()`",
"",
"到这里方向反过来了：不再是把数据放进去，而是**为某一个人取出来**。",
"",
"三个条件，缺一不可：",
"",
"```sql",
"WHERE is_open = 1                                    还挂着",
"  AND posted_at IS NOT NULL                          知道什么时候发的（硬条件）",
"  AND posted_at >= now - 36h                         够新",
"  AND NOT EXISTS (job_deliveries …)                  他没见过",
"```",
"",
"**36 小时不是 24**，而且是刻意的：早上 10 点那封信要够得着前一天下午的岗位，",
"严格 24 小时会把昨天上午之前发布的全部排除。",
"",
"**`posted_at IS NOT NULL` 是硬条件，没有退路分支** —— 这就是为什么第 ④ 层",
"「解析不出来返回 None」会直接决定一个岗位能不能被发出去。",
))
C.append(io("挑一个真实会员，把他此刻的候选池整个算出来并打印。",
            "生产 D1",
            "他的订阅偏好 + 候选池的每一行"))
C.append(code(
"layer(6, '一个人的候选池', 'the pool — same three conditions the sender uses')",
"",
"# 全部会员，全部信息 —— 这是你自己的库",
"subs = d1('SELECT s.account_id, e.email, e.plan, e.role, s.enabled, s.digest_slots, '",
"          \"       s.stack, s.role_families, s.regions, s.seniorities, s.home_region \"",
"          'FROM job_subscriptions s JOIN employers e ON e.id = s.account_id '",
"          'ORDER BY e.plan DESC, e.email')",
"print(f'   订阅表里 {len(subs)} 人\\n')",
"print(f'   {\"邮箱\":<34}{\"套餐\":<9}{\"角色\":<7}{\"开\":<4}{\"每天\":<5}地区')",
"for s in subs:",
"    print(f'   {s[\"email\"]:<34}{s[\"plan\"] or \"\":<9}{s[\"role\"] or \"\":<7}'",
"          f'{s[\"enabled\"]:<4}{str(s[\"digest_slots\"] or \"默认\"):<5}{s[\"home_region\"] or \"—\"}')",
"",
"ME = subs[0]",
"print(f'\\n   ── 拿 {ME[\"email\"]} 做例子 ──')",
"row(ME, '他的订阅设置（全部字段）：')",
"",
"audit('他的候选池现在有多少', '这三个条件就是发信真正用的那三个，一字不差。')",
"POOL = d1(f\"\"\"",
"SELECT j.id, j.title_raw, j.company, j.location_raw, j.region, j.role_family,",
"       j.role_group, j.seniority, j.salary_min, j.salary_max, j.posted_at",
"FROM jobs j",
"WHERE j.is_open = 1",
"  AND j.posted_at IS NOT NULL",
"  AND j.posted_at >= strftime('%s','now') - 36*3600",
"  AND NOT EXISTS (SELECT 1 FROM job_deliveries d",
"                  WHERE d.account_id = '{ME[\"account_id\"]}' AND d.job_id = j.id)",
"ORDER BY j.posted_at DESC LIMIT 400\"\"\")",
"verdict(len(POOL) > 0, f'候选池 {len(POOL)} 个',",
"        '0 个 → 这个人这一档会是 quiet。所有人都 0 → 链路断了，'",
"        '而那两件事在 digest_runs 里长得一模一样（2026-08-14 的事故）。')",
"",
"print(f'\\n   {\"年龄\":<7}{\"地区\":<15}{\"族\":<12}{\"级别\":<9}标题 @ 公司')",
"now_s = datetime.now(timezone.utc).timestamp()",
"for j in POOL[:25]:",
"    age = (now_s - j['posted_at'])/3600",
"    print(f'   {age:>4.0f}h  {(j[\"region\"] or \"—\"):<15}{(j[\"role_family\"] or \"—\"):<12}'",
"          f'{(j[\"seniority\"] or \"—\"):<9}{j[\"title_raw\"][:38]} @ {(j[\"company\"] or \"?\")[:22]}')",
"if len(POOL) > 25: print(f'   …还有 {len(POOL)-25} 个')",
"",
"audit('为什么有的岗位【不】在池子里', '被排除的原因有三种，修法完全不同。')",
"for label, sql in [",
"  ('已下架 is_open=0', 'is_open = 0'),",
"  ('没有发布时间（永远发不出去）', 'is_open = 1 AND posted_at IS NULL'),",
"  ('太老（超过 36 小时）', \"is_open = 1 AND posted_at IS NOT NULL AND posted_at < strftime('%s','now') - 36*3600\")]:",
"    n = d1(f'SELECT COUNT(*) n FROM jobs WHERE {sql}')[0]['n']",
"    print(f'     {label:<34}{n:>6}')",
"seen = d1(f\"SELECT COUNT(*) n FROM job_deliveries WHERE account_id = '{ME['account_id']}'\")[0]['n']",
"print(f'     {\"他已经收到过（不会重复）\":<30}{seen:>6}')",
))

# ══════════════════════ ⑦ 发出去的痕迹 ════════════════════════════════════
C.append(md(
"---",
"# ⑦ 一封邮件 + 四张台账 · what a send leaves behind",
"",
"**代码在** `send-digest.js:deliverDigest()`",
"",
"发一封信会写**四个地方**，各答一个不同的问题：",
"",
"| 表 | 回答 | 键 |",
"|---|---|---|",
"| `job_sends` | 他今天这一档收到几个岗位 | `(账号, 日期, 档)` |",
"| `digest_runs` | 这一次运行的**结局**（sent / quiet / failed / running）| 每次一行 |",
"| `digest_run_jobs` | **没进这封信**的岗位快照 —— 续页看到的就是它 | run × 岗位 |",
"| `job_deliveries` | 这个岗位**这辈子**发给他过 | `(账号, 岗位)` ← 刻意不带日期 |",
"",
"`digest_runs` 是 2026-08-11 才加的，为了一件事：**「跑了，但没有新岗位」也要留痕**。",
"在那之前只有 `job_sends`，而它只在真的发出一封信时写行 ——",
"于是「今天没岗位」和「定时器根本没跑」在库里长得一模一样。",
))
C.append(io("把这个人最近的发送痕迹四张表全部打印。",
            "生产 D1",
            "四张表的真实行"))
C.append(code(
"layer(7, '一封邮件 + 四张台账', 'what a send leaves behind')",
"aid = ME['account_id']",
"",
"print('   ── job_sends：他今天这一档收到几个 ──')",
"for r in d1(f\"SELECT day, slot, job_count, ok, error, created_at FROM job_sends \"",
"            f\"WHERE account_id='{aid}' ORDER BY day DESC, slot LIMIT 10\"):",
"    print(f'     {r[\"day\"]} {r[\"slot\"]:<10} {r[\"job_count\"]:>3} 个  ok={r[\"ok\"]}'",
"          f'  {r[\"error\"] or \"\"}')",
"",
"print('\\n   ── digest_runs：每一次运行的结局 ──')",
"runs = d1(f\"SELECT id, day, slot, trigger_kind, outcome, n_available, n_shown, \"",
"          f\"n_remainder, failure_stage, message FROM digest_runs \"",
"          f\"WHERE account_id='{aid}' ORDER BY day DESC, slot LIMIT 10\")",
"print(f'     {\"日期\":<12}{\"档\":<11}{\"触发\":<11}{\"结局\":<9}{\"可选\":>5}{\"发出\":>5}{\"剩余\":>5}')",
"for r in runs:",
"    print(f'     {r[\"day\"]:<12}{r[\"slot\"]:<11}{r[\"trigger_kind\"]:<11}{r[\"outcome\"]:<9}'",
"          f'{str(r[\"n_available\"]):>5}{str(r[\"n_shown\"]):>5}{str(r[\"n_remainder\"]):>5}'",
"          f'  {r[\"failure_stage\"] or \"\"}{(\" \"+r[\"message\"]) if r[\"message\"] else \"\"}')",
"",
"audit('失败的时候 counts 是 0 还是 NULL', '这个区别是刻意的，而且很重要。')",
"nulls = [r for r in runs if r['outcome'] in ('failed','running')]",
"verdict(all(r['n_shown'] is None for r in nulls) if nulls else True,",
"        f'{len(nulls)} 次失败/进行中的运行，counts 是 '",
"        f'{\"NULL\" if all(r[\"n_shown\"] is None for r in nulls) else \"0\"}' if nulls else '（最近没有失败的）',",
"        '失败时写 NULL 不写 0 —— 0 会被读成「今天没有岗位」，而那是完全不同的一件事。')",
"",
"if runs:",
"    R = runs[0]",
"    print(f'\\n   ── digest_run_jobs：{R[\"day\"]} {R[\"slot\"]} 那次【没发给他】的快照 ──')",
"    snap = d1(f\"SELECT rank, bucket, title_raw, company, location_raw, region, \"",
"              f\"posted_at, click_token, url FROM digest_run_jobs \"",
"              f\"WHERE run_id='{R['id']}' ORDER BY rank LIMIT 12\")",
"    for s in snap:",
"        print(f'     #{s[\"rank\"]:<4}{s[\"bucket\"]:<10}{s[\"title_raw\"][:40]:<42}'",
"              f'{(s[\"company\"] or \"?\")[:20]}')",
"    print(f'     （这一次共 {R[\"n_remainder\"]} 条快照）')",
"    print('\\n     快照是【发信那一刻的定格】：岗位之后下架了，那封信当时的样子也不变。')",
"    print('     所以 digest_run_jobs.job_id 刻意【不】对 jobs 建外键。')",
"",
"print(f'\\n   ── job_deliveries：这辈子发给他过的 ──')",
"dv = d1(f\"SELECT COUNT(*) n, MIN(day) first, MAX(day) last FROM job_deliveries WHERE account_id='{aid}'\")[0]",
"print(f'     {dv[\"n\"]} 个岗位，{dv[\"first\"]} → {dv[\"last\"]}')",
"print('     主键是 (账号, 岗位) —— 【不带日期】。')",
"print('     「今天发过了」和「这辈子发过了」是两个问题，用两把不同的键。')",
))

# ══════════════════════ ⑧ 会员看到什么 ════════════════════════════════════
C.append(md(
"---",
"# ⑧ 会员看到什么 · read back out",
"",
"**代码在** `functions/api/me/digests.js` + `my-jobs.html`",
"",
"门户读回来的**不是实时查询**，是第 ⑦ 层那份快照。这一点是设计，不是妥协：",
"",
"> 会员点开续页，看到的必须是**那封信当时的样子**。",
"> 岗位后来下架了、池子后来变了，都不该改变他收到的那封信。",
"",
"所有权是这样守的：`WHERE id = ? AND account_id = ?` —— ",
"别人的 run 和不存在的 run 返回**同一个 404**，不给出「存在但不属于你」这个信息。",
))
C.append(io("把「会员在门户上看到的那个 JSON」重建出来。",
            "生产 D1",
            "和 /api/me/digests 一样形状的结构"))
C.append(code(
"layer(8, '会员看到什么', 'read back out — the snapshot, not a live query')",
"if not runs:",
"    print('   这个人还没有任何 run，跳过。')",
"else:",
"    R = runs[0]",
"    counts = None if R['outcome'] in ('failed','running') else {",
"        'available': R['n_available'], 'shown': R['n_shown'], 'remainder': R['n_remainder']}",
"    shaped = {",
"        'runId': R['id'], 'day': R['day'], 'slot': R['slot'],",
"        'trigger': R['trigger_kind'], 'outcome': R['outcome'],",
"        'failureStage': R['failure_stage'], 'message': R['message'],",
"        'counts': counts,",
"        'hasRemainder': bool(R['n_remainder']),",
"    }",
"    print('   门户拿到的那个对象：')",
"    print(textwrap.indent(json.dumps(shaped, ensure_ascii=False, indent=2), '     '))",
"",
"    audit('failed / running 的时候 counts 给什么',",
"          '给 0 的话，界面会显示「今天 0 个岗位」—— 那是在替一次失败圆谎。')",
"    verdict(counts is not None or R['outcome'] in ('failed','running'),",
"            f\"outcome={R['outcome']} → counts={'null' if counts is None else '有数字'}\",",
"            'null 会让界面显示「出了点问题」而不是「今天没有岗位」。')",
"",
"    print(f'\\n   ── 续页 my-jobs.html?run={R[\"id\"]} 会列出 ──')",
"    print(f'     {R[\"n_remainder\"]} 个岗位，序号从 #{(R[\"n_shown\"] or 0)+1} 接下去')",
"    print('     排序和分桶都来自快照，页面自己不重新排。')",
"",
"audit('别人的 run 能不能被看到', '所有权检查写错了，就是一个人能读另一个人的邮件。')",
"other = d1(f\"SELECT id, account_id FROM digest_runs WHERE account_id != '{aid}' LIMIT 1\")",
"if other:",
"    print(f'     另一个人的 run：{other[0][\"id\"]}（属于 {other[0][\"account_id\"]}）')",
"    print(f'     查询条件是 WHERE id = ? AND account_id = ? —— 两个都要对上。')",
"    verdict(True, '别人的 run 和不存在的 run 返回同一个 404',",
"            '不给出「存在但不属于你」这个信息 —— 那本身就是信息。')",
))

# ══════════════════════ 全链路对账 ════════════════════════════════════════
C.append(md(
"---",
"# 全链路对账 · one row, end to end",
"",
"最后把一个岗位在**两个数据库、八层**里的样子并排放在一起。",
))
C.append(io("同一个岗位，从本地到生产，逐字段并排。",
            "两个库", "一张对照表"))
C.append(code(
"print(f'\\n{\"═\"*76}\\n  全链路对账 · {PAYLOAD[\"externalId\"]}\\n{\"═\"*76}\\n')",
"STAGES = [",
"  ('① 网页',       'HTML',        f'{len(CARD):,} 字的一张卡片'),",
"  ('② dict',      'python',      f'{len(JOB)} 个键，全是原文'),",
"  ('③ jobs.db',   'SQLite',      f'{len(dict(LOCAL))} 列'),",
"  ('④ 载荷',       'JSON',        f'{len(PAYLOAD)} 个键，postedAt 在这里算出来'),",
"  ('⑤ D1',        'D1',          f'{len(PROD)} 列，多出 region/族/级别/生命周期'),",
"  ('⑥ 候选池',     'SELECT',      f'{len(POOL)} 个（36 小时窗口 + 排除已投递）'),",
"  ('⑦ 台账',       '4 张表',      'job_sends / digest_runs / digest_run_jobs / job_deliveries'),",
"  ('⑧ 门户',       'JSON',        '快照，不是实时查询'),",
"]",
"for a, b, c in STAGES: print(f'  {a:<12}{b:<12}{c}')",
"",
"print(f'\\n  ── 同一个字段，在每一层叫什么 ──')",
"MAP = [('标题', JOB['title'][:30], dict(LOCAL).get('job_title','')[:30], PAYLOAD['title'][:30], PROD.get('title_raw','')[:30]),",
"       ('公司', JOB['company'][:24], dict(LOCAL).get('company','')[:24], (PAYLOAD['company'] or '')[:24], (PROD.get('company') or '')[:24]),",
"       ('地点', JOB['location'][:26], dict(LOCAL).get('location','')[:26], (PAYLOAD['location'] or '')[:26], (PROD.get('location_raw') or '')[:26]),",
"       ('时间', JOB['posted_date'], dict(LOCAL).get('posted_date',''), str(PAYLOAD['postedAt']), str(PROD.get('posted_at')))]",
"print(f'  {\"\":<6}{\"② dict\":<32}{\"③ jobs.db\":<32}{\"④ 载荷\":<26}⑤ D1')",
"for m in MAP: print(f'  {m[0]:<6}{m[1]:<32}{m[2]:<32}{m[3]:<26}{m[4]}')",
"",
"print('\\n  注意最后一行：只有【时间】在中途改变了类型。')",
"print('  那一次变换就是这条链路上唯一真正的 transform，也是出过两次事故的地方。')",
))

C.append(md(
"---",
"# 一个贯穿全程的形状",
"",
"这八层里出过的事故，形状完全一样：",
"",
"| | 表现 |",
"|---|---|",
"| 选择器失效 | 返回空字符串 |",
"| 函数没被调用 | 字段一直是空 |",
"| 解析失败 | 返回 None，或者更糟：回落到一个编出来的值 |",
"| 被 Cloudflare 拦住 | 「本页没有岗位」|",
"| 定时器没跑 | 和「今天没有新岗位」一模一样 |",
"| 全员 quiet | 和「一个人条件太窄」一模一样 |",
"",
"> **每一个失败都被渲染成了一个看起来正常的结果。**",
"> 这就是为什么这条链路上每一层都要有 audit —— 而不是等着它报错。",
))

nb = {"cells": C,
      "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                   "language_info": {"name": "python", "version": "3.12.0"}},
      "nbformat": 4, "nbformat_minor": 5}
for c in nb["cells"]:
    p = c["source"].split("\n")
    c["source"] = [l + "\n" for l in p[:-1]] + [p[-1]]

pathlib.Path("etl.ipynb").write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"etl.ipynb：{len(C)} 格（代码 {sum(1 for c in C if c['cell_type']=='code')}）")
